### ISSUE TITLE
Extra Utilities enchanter has no output

### ISSUE THREAD

**Issue by Krutoy242** [ProjectHDS/JEIExporter#2]
This is machine from Extra Utilities. It has default recipes:
![](https://i.imgur.com/Qbi42nh.png)

This is output file: 
[xu2_machine_extrautils2__enchanter.json.txt](https://github.com/ProjectHDS/JEIExporter/files/8472965/xu2_machine_extrautils2__enchanter.json.txt)

Output section of each recipe is empty:
```json
      "output": {
        "items": [
          {
            "amount": 0,
            "x": 70.0,
            "y": 4.0,
            "stacks": []
          }
        ]
      }
```

I found this usually happen when slots display not items, but there is definitely should be items.

**Comment by friendlyhj** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/blob/9e478a1f48b559c404747c663cbb29bd8acf93d9/1.10.2/src/main/java/com/rwtema/extrautils2/crafting/jei/JEIMachine.java#L184
That is XU2 issue. It puts empty list to the ingredient group. Generally, if you put ingredients to the group, jei will automatically render them to correct position. I also read the ingredient group to export information. But XU2 doesn't do it, but renders the output ingredients manually. I can't understand why it does that. I'm sorry that I have no idea to solve the issue.

**Comment by friendlyhj** [comment]
Maybe I can add a dependency?

**Comment by Krutoy242** [comment]
Well, XU2 has just few items in crafts, i could add them manually

**Comment by Krutoy242** [comment]
Where i can download this build? I cant see it in Releases tab.
